name: Nmap x86 Windows

on:
  workflow_dispatch

jobs:
  build:
    name: Build Nmap x86 Windows
    runs-on: windows-latest
    steps:    

    - name: Checkout
      uses: actions/checkout@v2

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.0
      with:
        vs-version: 12.0.21005.1

    - name: Install dependencies
      run: |
        #choco install --force --force-dependencies visualstudiocommunity2013 windows-sdk-8.1 dotnet4.0
        choco install --force --force-dependencies microsoft-build-tools --version=12.0.21005.1
        type 'C:\\ProgramData\\chocolatey\\logs\\chocolatey.log'
        git clone https://github.com/nmap/nmap.git "$env:GITHUB_WORKSPACE\nmap"
        svn checkout https://svn.nmap.org/nmap-mswin32-aux "$env:GITHUB_WORKSPACE\nmap-mswin32-aux"

    - name: Patch Nmap
      run: |
        cd "$env:GITHUB_WORKSPACE\nmap"
        pwd
        git apply --reject --whitespace=fix "$env:GITHUB_WORKSPACE\patches\nmap\fix-snprintf-macrodefinition-dnet-winconfig.patch"

    - name: Build Nmap x86 Windows
      run: |
        cd "$env:GITHUB_WORKSPACE\nmap\mswin32"
        #cp "$env:GITHUB_WORKSPACE\patches\nmap\nmap.rc" .
        $env:VCTargetsPath='C:\\Program Files (x86)\\MSBuild\\Microsoft.Cpp\\v4.0\\V140\\'
        ls 'C:\\Program Files (x86)\\MSBuild\\Microsoft.Cpp\\'
        ls 'C:\\Program Files (x86)\\MSBuild\\Microsoft.Cpp\\v4.0\\'
        ls 'C:\\Program Files (x86)\\MSBuild\\Microsoft.Cpp\\v4.0\\V140\\'
        Get-ChildItem -Path "C:\" -Filter "Microsoft.Build.CppTasks.Common.dll" -Recurse -ErrorAction SilentlyContinue -Force
        #& 'C:\Program Files (x86)\MSBuild\12.0\Bin\MSBuild.exe' nmap.sln /t:Build /p:Configuration=Release /p:PlatformToolset=v140
        #& 'C:\Program Files (x86)\MSBuild\12.0\Bin\MSBuild.exe' nmap.sln /t:Build /p:Configuration="Ncat Static" /p:Platform=x64
        & 'C:\Program Files (x86)\MSBuild\12.0\Bin\MSBuild.exe' nmap.sln /t:Build /p:Configuration="Release"
        

    - name: List directories
      run: |
        pwd
        ls
        ls  "$env:GITHUB_WORKSPACE\nmap\mswin32\"
        #ls  "$env:GITHUB_WORKSPACE\nmap\mswin32\Release"
