name: Nmap x86 Windows

on:
  workflow_dispatch

jobs:
  build:
    name: Build Nmap x86 Windows
    runs-on: windows-latest
    steps:    

    - name: Checkout
      uses: actions/checkout@v2

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.0
      with:
        vs-version: 15.0

    - name: Install dependencies
      run: |
        choco install --force --force-dependencies visualcpp-build-tools windows-sdk-8.1
        git clone https://github.com/nmap/nmap.git "$env:GITHUB_WORKSPACE\nmap"
        svn checkout https://svn.nmap.org/nmap-mswin32-aux "$env:GITHUB_WORKSPACE\nmap-mswin32-aux"

    - name: Patch Nmap
      run: |
        cd "$env:GITHUB_WORKSPACE\nmap"
        pwd
        git apply --reject --whitespace=fix "$env:GITHUB_WORKSPACE\patches\nmap\fix-snprintf-macrodefinition-dnet-winconfig.patch"

    - name: Build Nmap x86 Windows
      run: |
        cd "$env:GITHUB_WORKSPACE\nmap\mswin32"
        msbuild nmap.sln /t:Build /p:Configuration=Release /p:PlatformToolset=v141

    - name: List directories
      run: |
        pwd
        ls
        ls  "$env:GITHUB_WORKSPACE\nmap\mswin32\Release"
