name: Nmap x86 Windows

on:
  workflow_dispatch

jobs:
  build:
    name: Build Nmap x86 Windows
    runs-on: windows-latest
    steps:    

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.0
      with:
        vs-version: 12.0

    - name: Install dependencies
      run: |
        choco install --force --force-dependencies visualcpp-build-tools
        choco install --force --force-dependencies windows-sdk-8.1
        choco install --force --force-dependencies patch
        git clone https://github.com/nmap/nmap.git $GITHUB_WORKSPACE/nmap
        svn checkout https://svn.nmap.org/nmap-mswin32-aux $GITHUB_WORKSPACE/nmap-mswin32-aux

    - name: Patch Nmap
      run: |
        ls -la $GITHUB_WORKSPACE
        pwd
        patch $GITHUB_WORKSPACE\\nmap\\libdnet-stripped\\include\\dnet_winconfig.h < $GITHUB_WORKSPACE\\patches\\nmap\\fix-snprintf-macrodefinition-dnet-winconfig.patch
      shell: bash

    - name: Build Nmap x86 Windows
      run: |
        cd $GITHUB_WORKSPACE/nmap/mswin32
        msbuild nmap.sln /t:Build /p:Configuration=Release /p:PlatformToolset=v141

    - name: List directories
      run: |
        ls
        ls  $GITHUB_WORKSPACE/nmap/mswin32/Release/
      shell: powershell