name: Nmap x86_64
on:
  workflow_dispatch
jobs:
    build:
        name: Build Nmap x86_64
        runs-on: ubuntu-latest
        container: muslcc/x86_64:x86_64-linux-musl
        steps:
          - name: Install dependencies
            run: apk update && apk add bash git perl make cmake flex bison automake autoconf libtool qemu-arm qemu-aarch64 file texinfo zip
          - name: Checkout
            uses: actions/checkout@v2
          - name: Build Nmap
            run: $GITHUB_WORKSPACE/build/targets/build_nmap.sh x86_64
          - name: List build directory
            run: ls -la /build
          - name: List build artifacts
            run: ls -la /output
          - name: Package Nmap
            id: package_nmap
            run: $GITHUB_WORKSPACE/package/targets/nmap/package.sh /output x86_64
          - name: List packaged artifacts
            run: ls -la /packaged
          - name: Create release
            id: create_release
            uses: actions/create-release@v1
            env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            with:
              tag_name: ${{ github.ref }}
              release_name: Nmap x86_64 ${{ github.ref }}
              draft: false
              prerelease: false
          - name: Upload tarball
            uses: actions/upload-release-asset@v1
            env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            with:
              upload_url: ${{ steps.create_release.outputs.upload_url }} 
              asset_path: ${{ steps.package_nmap.outputs.PACKAGED_TARBALL_PATH }}
              asset_name: ${{ steps.package_nmap.outputs.PACKAGED_TARBALL }}
              asset_content_type: application/gzip
          - name: Upload zip
            uses: actions/upload-release-asset@v1
            env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            with:
              upload_url: ${{ steps.create_release.outputs.upload_url }}
              asset_path: ${{ steps.package_nmap.outputs.PACKAGED_ZIP_PATH }}
              asset_name: ${{ steps.package_nmap.outputs.PACKAGED_ZIP }}
              asset_content_type: application/zip
            
