# This is a basic workflow to help you get started with Actions

name: sshpass

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  workflow_dispatch:
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: muslcc/x86_64:x86_64-linux-musl
    steps:
    - name: Dependencies
      run: |
        apk update && apk add bash git perl make cmake flex bison automake autoconf libtool qemu-arm qemu-aarch64 file texinfo zip wget coreutils gawk glib-dev libgcrypt-dev c-ares-dev libssh-dev libpcap-dev
        ln -s /usr/bin/aclocal-1.16 /usr/bin/aclocal-1.15

    # Runs a single command using the runners shell
    - name: Build
      run: |
        git clone https://github.com/kevinburke/sshpass.git
        cd sshpass
        CFLAGS="-static -fPIC" ./configure
        CFLAGS="-static -fPIC" make
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
          name: sshpass
          path: /home/runner/work/workflow-test/workflow-test/sshpass/sshpass
