name: Nmap x86 Windows

on:
  workflow_dispatch

jobs:
  build:
    name: Build Nmap x86 Windows
    runs-on: windows-latest
    steps:    

    - name: Checkout
      uses: actions/checkout@v2

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.0
      with:
        vs-version: 15.0

    - name: Install dependencies
      run: |
        choco install --force --force-dependencies visualcpp-build-tools windows-sdk-8.1
        cd $GITHUB_WORKSPACE
        git clone https://github.com/nmap/nmap.git
        svn checkout https://svn.nmap.org/nmap-mswin32-aux

    - name: Patch Nmap
      run: |
        ls
        ls $GITHUB_WORKSPACE
        cd $GITHUB_WORKSPACE\\nmap
        git apply --reject --whitespace=fix $GITHUB_WORKSPACE\\patches\\nmap\\fix-snprintf-macrodefinition-dnet-winconfig.patch
      shell: bash

    - name: Build Nmap x86 Windows
      run: |
        cd $GITHUB_WORKSPACE\\nmap\\mswin32
        msbuild nmap.sln /t:Build /p:Configuration=Release /p:PlatformToolset=v141

    - name: List directories
      run: |
        ls
        ls  $GITHUB_WORKSPACE\\nmap\\mswin32\\Release\\
      shell: powershell