name: Nmap x86 Windows

on:
  workflow_dispatch

jobs:
  build:
    name: Build Nmap x86 Windows
    runs-on: windows-latest
    steps:    

    - name: Checkout
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        #choco install --force --force-dependencies visualstudio2019community windows-sdk-10.0
        #type 'C:\\ProgramData\\chocolatey\\logs\\chocolatey.log'
        git clone https://github.com/nmap/nmap.git "$env:GITHUB_WORKSPACE\nmap"
        svn checkout https://svn.nmap.org/nmap-mswin32-aux "$env:GITHUB_WORKSPACE\nmap-mswin32-aux"
        git clone https://github.com/robinrowe/libunistd.git "$env:GITHUB_WORKSPACE\libunistd"

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Patch Nmap
      run: |
        cd "$env:GITHUB_WORKSPACE\nmap"
        pwd
        #git apply --reject --whitespace=fix "$env:GITHUB_WORKSPACE\patches\nmap\fix-snprintf-macrodefinition-dnet-winconfig.patch"

    - name: Build Nmap x86 Windows
      run: |
        cd "$env:GITHUB_WORKSPACE\nmap\mswin32"
        pwd
        ls
        MSBuild.exe nmap.sln /t:Build /p:Configuration="Release" /p:IncludePath="$env:GITHUB_WORKSPACE\libunistd\unistd\"

    - name: List directories
      run: |
        pwd
        ls
        ls  "$env:GITHUB_WORKSPACE\nmap\mswin32\"
        #ls  "$env:GITHUB_WORKSPACE\nmap\mswin32\Release"
