name: tcpdump x86_64
on:
  workflow_dispatch
jobs:
    build:
        name: Build tcpdump x86_64
        runs-on: ubuntu-latest
        container: muslcc/x86_64:x86_64-linux-musl
        steps:

          - name: Build tcpdump
            run: |
              apk update && apk add flex bison wget make
              wget https://www.tcpdump.org/release/libpcap-1.9.1.tar.gz
              tar xzf libpcap-1.9.1.tar.gz
              cd libpcap-1.9.1/
              ./configure --with-pcap=linux
              make -j2
              export LIBPCAP_PATH=$(pwd)
              cd $GITHUB_WORKSPACE
              wget https://www.tcpdump.org/release/tcpdump-4.9.3.tar.gz
              tar xzf tcpdump-4.9.3.tar.gz
              cd tcpdump-4.9.3/
              export CFLAGS="-static -I${LIBPCAP_PATH} -L${LIBPCAP_PATH}"
              export CPPFLAGS=-static
              export LDFLAGS=-static
              ./configure
              make -j2

          - name: Upload artifacts
            uses: actions/upload-artifact@v2
            with:
                name: tcpdump-4.9.3
                path: /__w/static-toolbox/static-toolbox/tcpdump-4.9.3/tcpdump
