name: OpenSSH
on:
  workflow_dispatch
jobs:
    build-x86:
      name: Build OpenSSH x86
      runs-on: ubuntu-latest
      container: muslcc/x86_64:i686-linux-musl
      steps:
        - name: Checkout
          uses: actions/checkout@v2

        - name: Install dependencies
          run: sudo apk update && sudo apk add bash && sudo bash build/install_deps_alpine.sh

        - name: Build OpenSSH
          id: build_openssh
          run: $GITHUB_WORKSPACE/build/targets/build_openssh.sh x86

        - name: Upload artifacts
          uses: actions/upload-artifact@v2
          with:
              name: ${{ steps.build_openssh.outputs.PACKAGED_NAME }}
              path: ${{ steps.build_openssh.outputs.PACKAGED_NAME_PATH }}

    build-x86_64:
      name: Build OpenSSH x86_64
      runs-on: ubuntu-latest
      container: muslcc/x86_64:x86_64-linux-musl
      steps:
        - name: Checkout
          uses: actions/checkout@v2

        - name: Install dependencies
          run: sudo apk update && sudo apk add bash && sudo bash build/install_deps_alpine.sh

        - name: Build OpenSSH
          id: build_openssh
          run: $GITHUB_WORKSPACE/build/targets/build_openssh.sh x86_64

        - name: Upload artifacts
          uses: actions/upload-artifact@v2
          with:
              name: ${{ steps.build_openssh.outputs.PACKAGED_NAME }}
              path: ${{ steps.build_openssh.outputs.PACKAGED_NAME_PATH }}

    build-armhf:
      name: Build OpenSSH ARMHF
      runs-on: ubuntu-latest
      container: muslcc/x86_64:armel-linux-musleabihf
      steps:
        - name: Checkout
          uses: actions/checkout@v2

        - name: Install dependencies
          run: sudo apk update && sudo apk add bash && sudo bash build/install_deps_alpine.sh

        - name: Build OpenSSH
          id: build_openssh
          run: $GITHUB_WORKSPACE/build/targets/build_openssh.sh armhf

        - name: Upload artifacts
          uses: actions/upload-artifact@v2
          with:
              name: ${{ steps.build_openssh.outputs.PACKAGED_NAME }}
              path: ${{ steps.build_openssh.outputs.PACKAGED_NAME_PATH }}

    build-aarch64:
      name: Build OpenSSH AARCH64
      runs-on: ubuntu-latest
      container: muslcc/x86_64:aarch64-linux-musl
      steps:
        - name: Checkout
          uses: actions/checkout@v2

        - name: Install dependencies
          run: sudo apk update && sudo apk add bash && sudo bash build/install_deps_alpine.sh

        - name: Build OpenSSH
          id: build_openssh
          run: $GITHUB_WORKSPACE/build/targets/build_openssh.sh aarch64

        - name: Upload artifacts
          uses: actions/upload-artifact@v2
          with:
              name: ${{ steps.build_openssh.outputs.PACKAGED_NAME }}
              path: ${{ steps.build_openssh.outputs.PACKAGED_NAME_PATH }}