name: Nmap x86 Windows

on:
  workflow_dispatch

jobs:
  build:
    name: Build Nmap x86 Windows
    runs-on: windows-latest
    steps:    

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.0
      with:
        vs-version: 15.0

    - name: Install dependencies
      run: |
        choco install --force --force-dependencies visualcpp-build-tools
        choco install --force --force-dependencies windows-sdk-8.1
        git clone https://github.com/nmap/nmap.git $GITHUB_WORKSPACE/nmap
        svn checkout https://svn.nmap.org/nmap-mswin32-aux $GITHUB_WORKSPACE/nmap-mswin32-aux

    - name: Build Nmap x86 Windows
      run: |
        cd $GITHUB_WORKSPACE/nmap/mswin32
        msbuild nmap.sln /t:Build /p:Configuration=Release /p:PlatformToolset=v141

    - name: List directories
      run: |
        ls
        ls  $GITHUB_WORKSPACE/nmap/mswin32/Release/
      shell: powershell