name: strace AARCH64
on:
  workflow_dispatch
jobs:
    build:
        name: Build strace AARCH64
        runs-on: ubuntu-latest
        container: muslcc/i686:aarch64-linux-musl
        steps:

          - name: Install dependencies
            run: apk update && apk add bash git perl make cmake flex bison automake autoconf libtool qemu-arm qemu-aarch64 file texinfo zip wget coreutils gawk

          - name: Install build compiler
            run: /bin/sh -c "apk update && apk upgrade && apk add --no-cache curl rsync sudo util-linux && cd / && curl -so ${ARCH}-cross.tgz ${HOST}/${ARCH}-cross.tgz && tar -xf ${ARCH}-cross.tgz && rm ${ARCH}-cross.tgz && cd ${ARCH}-cross"
            env:
                ARCH: i686-linux-musl
                HOST: https://more.musl.cc/9.2.1/i686-linux-musl
                TEMP: /tmp
                USER: 0

          - name: Checkout
            uses: actions/checkout@v2

          - name: Build strace
            id: build_strace
            run: $GITHUB_WORKSPACE/build/targets/build_strace.sh aarch64

          - name: List build directory
            run: ls -la /build

          - name: List build artifacts
            run: ls -la /output

          - name: Upload artifacts
            uses: actions/upload-artifact@v2
            with:
                name: ${{ steps.build_strace.outputs.PACKAGED_NAME }}
                path: ${{ steps.build_strace.outputs.PACKAGED_NAME_PATH }}
