name: tcpdump
on:
  workflow_dispatch
jobs:
    build-x86:
      name: Build tcpdump x86
      runs-on: ubuntu-latest
      container: muslcc/x86_64:i686-linux-musl
      steps:
        - name: Checkout
          uses: actions/checkout@v2

        - name: Install dependencies
          run: sudo apk update && sudo apk add bash && sudo bash build/install_deps_alpine.sh

        - name: Build tcpdump
          id: build_tcpdump
          run: $GITHUB_WORKSPACE/build/targets/build_tcpdump.sh x86

        - name: Upload artifacts
          uses: actions/upload-artifact@v2
          with:
              name: ${{ steps.build_tcpdump.outputs.PACKAGED_NAME }}
              path: ${{ steps.build_tcpdump.outputs.PACKAGED_NAME_PATH }}

    build-x86_64:
      name: Build tcpdump x86_64
      runs-on: ubuntu-latest
      container: muslcc/x86_64:x86_64-linux-musl
      steps:
        - name: Checkout
          uses: actions/checkout@v2

        - name: Install dependencies
          run: sudo apk update && sudo apk add bash && sudo bash build/install_deps_alpine.sh

        - name: Build tcpdump
          id: build_tcpdump
          run: $GITHUB_WORKSPACE/build/targets/build_tcpdump.sh x86_64

        - name: Upload artifacts
          uses: actions/upload-artifact@v2
          with:
              name: ${{ steps.build_tcpdump.outputs.PACKAGED_NAME }}
              path: ${{ steps.build_tcpdump.outputs.PACKAGED_NAME_PATH }}

    build-armhf:
      name: Build tcpdump ARMHF
      runs-on: ubuntu-latest
      container: muslcc/x86_64:arm-linux-musleabihf
      steps:
        - name: Checkout
          uses: actions/checkout@v2

        - name: Install dependencies
          run: sudo apk update && sudo apk add bash && sudo bash build/install_deps_alpine.sh

        - name: Build tcpdump
          id: build_tcpdump
          run: $GITHUB_WORKSPACE/build/targets/build_tcpdump.sh armhf

        - name: Upload artifacts
          uses: actions/upload-artifact@v2
          with:
              name: ${{ steps.build_tcpdump.outputs.PACKAGED_NAME }}
              path: ${{ steps.build_tcpdump.outputs.PACKAGED_NAME_PATH }}

    build:
      name: Build tcpdump AARCH64
      runs-on: ubuntu-latest
      container: muslcc/x86_64:aarch64-linux-musl
      steps:
        - name: Checkout
          uses: actions/checkout@v2

        - name: Install dependencies
          run: sudo apk update && sudo apk add bash && sudo bash build/install_deps_alpine.sh

        - name: Build tcpdump
          id: build_tcpdump
          run: $GITHUB_WORKSPACE/build/targets/build_tcpdump.sh aarch64

        - name: Upload artifacts
          uses: actions/upload-artifact@v2
          with:
              name: ${{ steps.build_tcpdump.outputs.PACKAGED_NAME }}
              path: ${{ steps.build_tcpdump.outputs.PACKAGED_NAME_PATH }}
