name: mimikatz x86_64 Windows

on:
  workflow_dispatch

jobs:
  build:
    name: Build mimikatz x86_64 Windows
    runs-on: windows-latest
    steps:    

    - name: Checkout
      uses: actions/checkout@v2

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.0
      with:
        vs-version: 12.0

    - name: Install dependencies
      run: |
        choco install --force --force-dependencies visualcpp-build-tools windows-sdk-8.1
        git clone https://github.com/gentilkiwi/mimikatz.git "$env:GITHUB_WORKSPACE\mimikatz"

    - name: Build mimikatz x86_64 Windows
      run: |
        cd "$env:GITHUB_WORKSPACE\mimikatz"
        msbuild mimikatz.sln /t:Build /p:Configuration=Release /p:PlatformToolset=v120

    - name: List directories
      run: |
        pwd
        ls
        ls  "$env:GITHUB_WORKSPACE\mimikatz"
