# This is a basic workflow to help you get started with Actions

name: Nmap x86 Windows

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  workflow_dispatch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.0
      with:
        vs-version: 15.0

    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Clone Nmap repo
      run: git clone https://github.com/nmap/nmap.git
    
    - name: List current dir
      run: ls
      shell: powershell

    # Runs a set of commands using the runners shell
    - name: Run some commands
      run: |
        msbuild /version
        whoami
      shell: powershell
