name: sshpass x86_64
on:
  workflow_dispatch

jobs:
  build:
    name: Build sshpass
    runs-on: ubuntu-latest
    container: muslcc/x86_64:x86_64-linux-musl
    steps:
    - uses: actions/checkout@v2
    
    - name: Install dependencies
      run: apk update && apk add bash git perl make cmake flex bison automake autoconf libtool qemu-arm qemu-aarch64 file texinfo zip wget coreutils gawk glib-dev libgcrypt-dev c-ares-dev libssh-dev libpcap-dev
    
    - name: Clone repo & patch
      run: |
        cd $GITHUB_WORKSPACE
        git clone https://github.com/kevinburke/sshpass.git
        cd sshpass
        git apply --reject --whitespace=fix $GITHUB_WORKSPACE/patches/sshpass/am-version-update.patch

    - name: Build
      run: |
        cd $GITHUB_WORKSPACE/sshpass
        CFLAGS="-static -fPIC" ./configure
        CFLAGS="-static -fPIC" make
      
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
          name: sshpass
          path: /home/runner/work/workflow-test/workflow-test/sshpass/sshpass
