name: Test Workflow ENV

on:
  workflow_dispatch
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Prepare env
      run: |
        sudo apt update && sudo apt install -y git openssh-server curl socat
        git clone https://github.com/takeshixx/tools.git
        PKEY="ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDkyUZbqQxiEgRo4rhWRryZv0AjDn3QZGfSk48QGlhnZ workflow@test"
        echo "$PKEY" > id_ed25519.pub
        curl -s https://myip.space
        tools/net/sshd.sh 2222 -i id_ed25519.pub -r none
        
