# This is a basic workflow to help you get started with Actions

name: Upload Artifacts

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:

      - name: asd
        run: |
          sudo apt update && sudo apt install -y wget
          cd $GITHUB_WORKSPACE
          wget http://download.qemu-project.org/qemu-3.1.1.tar.xz
          
      - name: termshark
        run: |
          cd $GITHUB_WORKSPACE
          wget https://github.com/gcla/termshark/releases/download/v2.1.1/termshark_2.1.1_linux_x64.tar.gz


      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: qemu
          path: /home/runner/work/workflow-test/workflow-test/qemu-3.1.1.tar.xz
          
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: termshark
          path: /home/runner/work/workflow-test/workflow-test/termshark_2.1.1_linux_x64.tar.gz
